- hosts: localhost
  vars_files:
    - ./script_vars.yaml
  tasks:
        - name: clean up
          shell: rm -rf {{ project_name }}
        - name: clone project from github
          shell: git clone {{ git_repo }}
        - name: traverse to repository and checkout from baseline
          shell:  cd {{ local_path }} && git checkout {{ baseline_branch }}
        - name: compile the package for channel1
          shell:  cd {{ local_path }} && mvn clean package
          register: mvn_result
        - name: Output of compilation of package for baseline
          debug:
            var: mvn_result   
        - name: Operations for channel1
          shell:  cd {{ local_path }}  
                  && git checkout -b {{ release_channel1 }}
                  && git push origin {{ release_channel1 }}
          register: channl1_result
        - name: Output of operations for channel1
          debug:
            var: channl1_result
        - name: Branch checkout for channel2
          shell:  cd {{ local_path }}
                  && git checkout -b {{ release_channel2 }}
          register: channl2_checkout_result
        - name: Output of branch checkout for channel2
          debug:
            var: channl2_checkout_result           
        - name: Update pom artifactId for API
          replace: 
                  path: "{{local_path}}/pom.xml" 
                  regexp: "<artifactId>{{ channel1_artifactId}}</artifactId>"
                  replace: "<artifactId>{{ channel2_artifactId }}</artifactId>"
          register: pom_artifactId_result
        - name: Output of Update pom artifactId for API
          debug:
            var: pom_artifactId_result          
        - name: Update name of API in pom.xml
          replace: 
                  path: "{{local_path}}/pom.xml"
                  regexp: "<name>{{ channel1_api }}</name>"
                  replace: "<name>{{ channel2_api }}</name>"
          register: pom_api_result
        - name: compile the package for channel2
          shell:  cd {{ local_path }} && mvn clean package
          register: mvn_result
        - name: Output of compilation of package for channel2
          debug:
            var: mvn_result           
        - name: Git Operations for channel2
          shell:  cd {{ local_path }}  
                  && git commit -am "update channel specific details"
                  && git push origin {{ release_channel2 }}
          register: channl2_result
        - name: Output Git Operations for channel2
          debug:
            var: channl2_result                              
          
                                  